## Misc stuff
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/lib:$PATH"
export PATH="/Applications/CMake.app/Contents/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.npm:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
export LC_ALL=en_GB.UTF-8
export CLASSPATH="/Users/$USER/javadev/"
export PYTHON="/usr/bin/python3"
export DOCKER_ID_USER="therealdannzor"
export ZSH=/Users/$USER/.oh-my-zsh

## Shortcuts
alias cs='cd ~/go/src/github.com/therealdannzor/cs'
alias cfg='nvim ~/.config/nvim/init.vim'
alias plg='nvim ~/.config/nvim/cfg/plugins.vim'
alias r='ranger'
alias c='clear'
alias x='exit'
alias m='make test'
alias mc='mvn clean compile assembly:single'
alias cl++='clang++ -Wall -std=c++11'
alias uzr='source ~/.zshrc'

## Golang
export GO111MODULE=on
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec/"
export GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

## Android development
export ANDROID_HOME="/Users/$USER/Library/Android/sdk"
export ANDROID_NDK="/Users/$USER/Library/Android/sdk/ndk-bundle"


ZSH_THEME=apple

plugins=(
  git
)

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
plugins=(git colorize bundler)

source $ZSH/oh-my-zsh.sh


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS=“dd.mm.yyyy”

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/users/kadanis/.oh-my-zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
#

## Other exports
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export CPPFLAGS="-I/usr/local/opt/libffi/include"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
