
## Misc stuff
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/lib:$PATH"
export PATH="/Applications/CMake.app/Contents/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.npm:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
export EDITOR=$(which vim)

export LC_ALL=en_GB.UTF-8
export CLASSPATH="/Users/$USER/Development/Java/"
export PYTHON="/usr/bin/python3"
export DOCKER_ID_USER="therealdannzor"
export ZSH=/Users/$USER/.oh-my-zsh

## Shortcuts
alias cfg='nvim ~/.config/nvim/init.vim'
alias plg='nvim ~/.config/nvim/cfg/plugins.vim'
alias uzr='exec zsh'
alias r='ranger'
alias c='clear'
alias x='exit'
alias e='exa -l --no-user --no-permissions --git'
alias t='tmux attach || tmux'
alias kp='kill $(lsof -t -i:8081)'
alias reth='cd ~/go/src/github.com/therealdannzor/reth'

## Golang
export GO111MODULE=on
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export GOROOT="/usr/local/go"
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# Rust
export RUSTFMT_CONFIG_PATH="/Users/$USER/.config/rustfmt/rustfmt.toml"
export PATH=~/.local/share/solana/install/active_release/bin:$PATH

## Android development
#export ANDROID_HOME="$HOME/Library/Android/sdk"
#export ANDROID_NDK="$HOME/Library/Android/sdk/ndk-bundle"

## Hunter pkg management
#export HUNTER_ROOT="$HOME/.hunter"

## Other exports
#export LDFLAGS="-L/usr/local/opt/libffi/lib"
#export CPPFLAGS="-I/usr/local/opt/libffi/include"
#export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
#LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
#export PATH="/usr/local/opt/llvm/bin:$PATH"
#export LDFLAGS="-L/usr/local/opt/llvm/lib"
#export CPPFLAGS="-I/usr/local/opt/llvm/include"
#export PATH="/usr/local/opt/python@3.8/bin:$PATH"
#export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"
#export LDFLAGS="-L/usr/local/opt/python@3.8/lib"
#export PATH="/usr/local/opt/openjdk/bin:$PATH"
#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
#export PATH="/usr/local/opt/mysql-client/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
# export LDFLAGS="-L/usr/local/opt/llvm/bin"
# export PATH="/usr/local/opt/llvm/bin:$PATH"
# export CPPFLAGS="-I/usr/local/opt/llvm/include"
#export PATH="/usr/local/opt/mysql-client/bin:$PATH"

#export DISPLAY="/private/tmp/com.apple.launchd.wUPsLLErHn/org.xquartz:0"
#export DISPLAY="/private/tmp/com.apple.launchd.EpRgTqDBPw/org.xquartz:0"

# useful only for Mac OS Silicon M1
docker() {
 if [[ `uname -m` == "arm64" ]] && [[ "$1" == "run" || "$1" == "build" ]]; then
    /usr/local/bin/docker "$1" --platform linux/amd64 "${@:2}"
  else
     /usr/local/bin/docker "$@"
  fi
}


ZSH_THEME=apple

plugins=(
  git
  colorize
  bundler
  tmux
)

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#plugins=(git colorize bundler)

source $ZSH/oh-my-zsh.sh

function ask_chatgpt {
  echo "hiho"
  typeset prompt="${1#*([[:space:]])}"
  typeset response=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $GPT_API_KEY" -d "{\"prompt\": \"$prompt\", \"temperature\": 0.5, \"max_tokens\": 300, \"model\": \"text-davinci-002\"}" https://api.openai.com/v1/completions | sed 's/\\n//g')

  if [ "$(echo $response | jq '.choices')" != "[]" ]; then
	typeset text=$(echo $response | jq -r '.choices[0].text')
	echo "$text"
  else
	local error=$(echo $response | jq -r '.error.message')
	echo "Error: $error"
  fi
}
