## Misc stuff
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/lib:$PATH"
export PATH="/Applications/CMake.app/Contents/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.npm:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
export EDITOR=$(which vim)

export LC_ALL=en_GB.UTF-8
export CLASSPATH="/Users/$USER/Development/Java/"
export PYTHON="/usr/bin/python3"
export DOCKER_ID_USER="therealdannzor"
export ZSH=/Users/$USER/.oh-my-zsh

## Shortcuts
alias cfg='nvim ~/.config/nvim/init.vim'
alias plg='nvim ~/.config/nvim/cfg/plugins.vim'
alias uzr='exec zsh'
alias r='ranger'
alias c='clear'
alias x='exit'
alias e='exa -l --no-user --no-permissions --git'

## Various dev
alias m='make test'
alias mc='mvn clean compile assembly:single'
alias cl++='clang++ -Wall -std=c++11'

## Golang
export GO111MODULE=on
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export GOROOT="/usr/local/Cellar/go/1.16.5/libexec/"
export GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

## Android development
export ANDROID_HOME="$HOME/Library/Android/sdk"
export ANDROID_NDK="$HOME/Library/Android/sdk/ndk-bundle"

## Hunter pkg management
export HUNTER_ROOT="$HOME/.hunter"

## Other exports
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export CPPFLAGS="-I/usr/local/opt/libffi/include"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
export PATH="/usr/local/opt/python@3.8/bin:$PATH"
export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"
export LDFLAGS="-L/usr/local/opt/python@3.8/lib"
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
#export PATH="/usr/local/opt/mysql-client/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
# export LDFLAGS="-L/usr/local/opt/llvm/bin"
# export PATH="/usr/local/opt/llvm/bin:$PATH"
# export CPPFLAGS="-I/usr/local/opt/llvm/include"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

#export DISPLAY="/private/tmp/com.apple.launchd.wUPsLLErHn/org.xquartz:0"
export DISPLAY="/private/tmp/com.apple.launchd.EpRgTqDBPw/org.xquartz:0"



ZSH_THEME=apple

plugins=(
  git
)

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
plugins=(git colorize bundler)

source $ZSH/oh-my-zsh.sh
